# Generated by Django 3.1 on 2020-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snip_pit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_by',
            field=models.CharField(blank=True, choices=[('Ian Malcolm', 'Ian Malcolm'), ('John Hammond', 'John Hammond'), ('Alan Grant', 'Alan Grant'), ('Dennis Nedry', 'Dennis Nedry'), ('Dr Henry Wu', 'Dr Henry Wu'), ('Ray Arnold', 'Ray Arnold')], default=' ', max_length=254, null=True),
        ),
    ]
